spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymtracker
    username: gym
    password: gym
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
server:
  port: 8080
app:
  cors:
    allowed-origins: http://localhost:5173
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
